/**
 * THE FRONT DOOR: the HTML title screen, and the idle handoff to the decoded
 * canvas attract behind it.
 *
 * ---------------------------------------------------------------------------
 * WHAT THIS IS, AND WHAT IT DELIBERATELY IS NOT
 * ---------------------------------------------------------------------------
 * Pinball Fantasies HD boots to an HTML page: a CSS-gradient wordmark, one
 * thumbnail card per table with a champion line, a key legend, and cards that
 * boot straight into a game (`shell-main.ts` there). The operator asked for
 * "the same kind of title screen", and this module is that page for
 * Illusions — with one deliberate difference the brief records: Fantasies has
 * no attract cycling because its 1992 shell had none to lose, while Illusions'
 * decoded shell authentically DOES (the disk's own twelve credit pages over
 * the tumbling-object backdrops, film-verified to the frame). So the canvas
 * attract is not deleted; it is DEMOTED to the idle behaviour behind this
 * door. After `ATTRACT_IDLE_TICKS_MS` without a key or a pointer the door
 * steps aside and the filmed roll plays; activity brings the door back. SPACE
 * from that roll still opens the decoded menu / table select / info screens,
 * exactly as the machine's own front end works — the authentic navigation is
 * reachable, merely no longer the entry.
 *
 * ---------------------------------------------------------------------------
 * WHY THE MODULE FILLS A PAGE RATHER THAN BUILDING ONE
 * ---------------------------------------------------------------------------
 * The card structure lives in `index.html` and this module only writes the
 * DATA into it — names and blurbs from `SHELL_TABLES` (the same records the
 * decoded info screens print), champion lines from the same five-slot ladder
 * the canvas shell shows, the version from the build. That is the split the
 * touch layer already uses, and it is what makes this file testable against
 * `tests/dom-harness.ts`: the test builds its fixture FROM the shipped markup,
 * so a renamed attribute fails a test instead of silently unhooking a card.
 *
 * No game logic lives here. The one thing a card DOES is call the host's
 * `playTable`, which goes through `shellPlayTable` — the decoded F-key path —
 * so a click and a function key end up in exactly the same state.
 */

import { SHELL_TABLES, shellTableFor } from "./shell.js";
import type { ShellPhase } from "./shell.js";
import type { HighScoreEntry } from "../game/high-scores.js";
import type { TableId } from "../game/contracts.js";

/**
 * Idle milliseconds on the door before the decoded attract takes the screen.
 * The brief suggests thirty seconds; nothing film-verified constrains it —
 * the machine's own roll IS its idle screen, this is only how long the HTML
 * page waits before yielding to it.
 */
export const ATTRACT_IDLE_MS = 30_000;

/** Where the card thumbnails ship. Generated by `scripts/export-shell-thumbs.mjs`. */
export function doorThumbUrl(tableId: TableId): string {
  return `generated/shell/${tableId}-thumb.webp`;
}

/** The champion line: the local ladder's top slot, Fantasies' card format. */
export function championLine(ladder: readonly HighScoreEntry[]): string {
  const top = ladder[0];
  if (top === undefined || top.score <= 0) return "No score yet";
  return `★ ${top.initials.trim().length === 0 ? "???" : top.initials} · ${top.score.toLocaleString("en-US")}`;
}

/** What the host supplies. Everything else is read off the document. */
export interface FrontDoorHost {
  /** Boots a table exactly as the decoded F-keys do (`shellPlayTable`). */
  playTable(tableId: TableId): void;
  /** The five-slot ladder for one table, for the champion line. */
  ladder(tableId: TableId): readonly HighScoreEntry[];
  /** A gesture landed on the door; the audio unlock rides it. */
  gesture(): void;
  /** The build's version string, for the footer. */
  version(): string;
}

/**
 * What the page is showing, reflected onto `<html data-door-mode>` for the
 * stylesheet: the door, the canvas (attract or menus), or a running table
 * (which is when the desktop game bar shows).
 */
export type DoorMode = "door" | "canvas" | "game";

export interface FrontDoor {
  /**
   * Reflects the shell's phase, the loaded table and the idle clock onto the
   * DOM. Call once a frame, the way the touch deck's `refresh` is called.
   */
  refresh(phase: ShellPhase, tableId: TableId | null, nowMs: number): void;
  /** Records player activity: the idle clock restarts, the door returns. */
  noteActivity(nowMs: number): void;
  /** True while the HTML door is the thing on screen. */
  showing(): boolean;
  /** True while the idle canvas attract is the thing on screen. */
  idling(): boolean;
  /** The mode last painted, for the host's own routing decisions. */
  mode(): DoorMode;
  /** Repaints the champion lines, for after a game banks a score. */
  refreshChampions(): void;
  detach(): void;
}

/** Phases on which the door may cover the screen: the canvas attract only. */
function phaseAllowsDoor(phase: ShellPhase): boolean {
  return phase === "attract";
}

/** Phases over a loaded table, where the game bar belongs. */
function phaseIsGame(phase: ShellPhase): boolean {
  switch (phase) {
    case "play":
    case "quit-confirm":
    case "game-over":
    case "fanfare":
    case "initials":
    case "ladder":
    case "loading":
      return true;
    default:
      return false;
  }
}

/**
 * Wires the door. The document is taken from the element, exactly as
 * `attachTouch` takes it from the canvas, so the whole thing runs inside the
 * test harness's fake DOM.
 */
export function attachFrontDoor(door: HTMLElement, host: FrontDoorHost): FrontDoor {
  const document = door.ownerDocument;
  const root = document.documentElement;

  const bindings: { target: HTMLElement; type: string; listener: EventListener }[] = [];
  const on = (target: HTMLElement, type: string, listener: EventListener): void => {
    target.addEventListener(type, listener);
    bindings.push({ target, type, listener });
  };

  // -- the card data, written once from the same records the shell reads ----

  const champions = new Map<TableId, HTMLElement>();

  for (const table of SHELL_TABLES) {
    const name = door.querySelector(`[data-door-name="${table.id}"]`);
    if (name instanceof HTMLElement) name.textContent = table.name;
    // The blurb lines were written for the info screen's narrow column; on a
    // card they read as one sentence, so they are joined the way the eye
    // joins them there.
    const blurb = door.querySelector(`[data-door-blurb="${table.id}"]`);
    if (blurb instanceof HTMLElement) blurb.textContent = table.blurb.join(" ");
    const champ = door.querySelector(`[data-door-champ="${table.id}"]`);
    if (champ instanceof HTMLElement) champions.set(table.id, champ);

    const thumb = door.querySelector(`[data-door-thumb="${table.id}"]`);
    if (thumb instanceof HTMLElement) {
      // A build without the gated thumbnails (or a fetch that fails) keeps
      // the CSS placeholder rather than a broken-image glyph.
      on(thumb, "error", () => {
        thumb.hidden = true;
      });
      thumb.setAttribute("src", doorThumbUrl(table.id));
    }

    const card = door.querySelector(`[data-door-table="${table.id}"]`);
    if (card instanceof HTMLElement) {
      on(card, "click", (event) => {
        // The href stays for middle-click and link sharing (`?table=` boots
        // straight in, Fantasies' own URL contract); a plain click plays
        // without a reload.
        event.preventDefault();
        host.gesture();
        host.playTable(table.id);
      });
    }
  }

  const paintChampions = (): void => {
    for (const [tableId, element] of champions) {
      const line = championLine(host.ladder(tableId));
      if (element.textContent !== line) element.textContent = line;
    }
  };
  paintChampions();

  const version = door.querySelector("[data-door-version]");
  if (version instanceof HTMLElement) version.textContent = host.version();

  // The game bar's title: the loaded table's name, painted by refresh.
  const barTitle = document.querySelector("[data-bar-title]");

  // -- the idle clock and the three-way mode --------------------------------

  let lastActivity = Number.NEGATIVE_INFINITY;
  let painted: DoorMode | null = null;
  let currentTable: TableId | null = null;
  /**
   * True only while the canvas holds the screen BECAUSE the idle window
   * elapsed on the attract roll — never while the decoded menus own it. The
   * distinction is what lets the host treat a key during the idle attract as
   * "wake the door" without ever stealing a keystroke from a menu.
   */
  let idleAttract = false;

  const paint = (mode: DoorMode, tableId: TableId | null): void => {
    if (mode !== painted) {
      painted = mode;
      door.hidden = mode !== "door";
      root.dataset["doorMode"] = mode;
      if (mode === "door") paintChampions();
    }
    if (tableId !== currentTable) {
      currentTable = tableId;
      if (barTitle instanceof HTMLElement) {
        barTitle.textContent = tableId === null ? "" : shellTableFor(tableId).name;
      }
    }
  };

  return {
    refresh: (phase, tableId, nowMs) => {
      if (!phaseAllowsDoor(phase)) {
        // Any screen that is not the attract roll owns the canvas: the
        // decoded menus, the loading card, and the table itself. The idle
        // clock re-seeds so leaving a game does not instantly idle out.
        lastActivity = nowMs;
        idleAttract = false;
        paint(phaseIsGame(phase) ? "game" : "canvas", gameBarTable(phase, tableId));
        return;
      }
      if (lastActivity === Number.NEGATIVE_INFINITY) lastActivity = nowMs;
      idleAttract = nowMs - lastActivity >= ATTRACT_IDLE_MS;
      paint(idleAttract ? "canvas" : "door", null);
    },
    noteActivity: (nowMs) => {
      lastActivity = nowMs;
    },
    showing: () => painted === "door",
    idling: () => painted === "canvas" && idleAttract,
    mode: () => painted ?? "door",
    refreshChampions: paintChampions,
    detach: () => {
      for (const binding of bindings) {
        binding.target.removeEventListener(binding.type, binding.listener);
      }
      bindings.length = 0;
    },
  };
}

/**
 * The table the game bar should name, given the shell's own state. Split out
 * so the host's one call site stays a line.
 */
export function gameBarTable(phase: ShellPhase, tableId: TableId | null): TableId | null {
  return phaseIsGame(phase) ? tableId : null;
}
